### ISSUE TITLE
cannot resolve org.springframework.cloud:spring-cloud-starter-config

### ISSUE THREAD

**Issue by tanuja3088** [spring-cloud/spring-cloud-release#100]
I am using gradle to build and here is my build.gradle

Is there anything that I am missing

repositories {
    mavenCentral()
    maven { url "https://repo.spring.io/libs-milestone" }
    maven { url "https://repo.spring.io/libs-snapshot" }

}

apply plugin: 'org.springframework.boot'
apply plugin: 'java'
apply plugin: 'javac2'
apply plugin: 'docker'

dependencies {
    compile project(':services')
    compile 'org.springframework.boot:spring-boot-starter-web'
    compile('org.springframework.cloud:spring-cloud-starter-config')
    compile('org.springframework.boot:spring-boot-starter-actuator')
    compile 'org.jetbrains:annotations:13.0'
    runtime 'org.aspectj:aspectjweaver'

    testCompile 'junit:junit'
    testCompile 'org.springframework.boot:spring-boot-starter-test'
    testRuntime "com.jayway.awaitility:awaitility:$awaitilityVersion"
    testRuntime 'com.jayway.jsonpath:json-path'
}

apply plugin: 'java'

springBoot {
    executable = true
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:Finchley.BUILD-SNAPSHOT"
    }
}

docker {
    baseImage "java:8"
}

task buildDocker(type: Docker, dependsOn: build) {
    applicationName = "ldp-data-fetcher"
    exposePort(8080)
    addFile("${buildDir}/libs/app-0.1-SNAPSHOT.jar", "/opt/jmg/app-0.1-SNAPSHOT.jar")
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

The best thing to do is to generate the project using start.spring.io and try to build that.  If it still doesnt work than there is probably something wrong with your local maven repo, try clearing it and building again.
