### ISSUE TITLE
spriing boot with eureka 

### ISSUE THREAD

**Issue by srinivasvadla** [spring-cloud/spring-cloud-release#106]
Hai all .
could you pleases help out this error in pom.xml , iam using spring boot with eureka when iam adding the below dependency it is saying --:**Project build error: 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-starter-eureka:jar is missing.
org.springframework.cloud spring-cloud-starter-eureka**

My Boot version is below one
2.1.0.RELEASE

Thank you,
Srinivas.

**Comment by spencergibb** [comment]
Please stop opening multiple issues
