### ISSUE TITLE
Can't find Greenwich in repo.maven.apache.org

### ISSUE THREAD

**Issue by ackintosh** [spring-cloud/spring-cloud-release#107]
Question

I'd like to use `Greenwich` with Spring Boot 2.1 but couldn't install it as `Greenwich` can't be found in repo.maven.apache.org.
http://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-dependencies/

Could you register `Greenwich` to the repo?
(Sorry if I missed the point of issue, I'm not familiar with Java/Spring/etc... 💦 )

**Comment by ebussieres** [comment]
It's in the spring milestone repository. You need to add a repository in your pom.xml

```
<repositories>
    <repository>
        <id>spring-milestones</id>
        <name>Spring Milestones</name>
        <url>http://repo.spring.io/milestone</url>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>
</repositories>
```

**Comment by spencergibb** [comment]
What @ebussieres said. Only final releases go to maven central.
