### ISSUE TITLE
Greenwich.RELEASE: spring-security-oauth2-autoconfigure version unavailable

### ISSUE THREAD

**Issue by TruthNZ** [spring-cloud/spring-cloud-release#108]
The version of spring-security-oauth2-autoconfigure (2.10.M4) specified in Greenwich.RELEASE isn't publically available in the same repositories as Greenwich.RELEASE itself and other dependencies specified by it - in particular maven central.

Simple enough to work around by excluding it as a transitive dependency and specifically fetching a publically available version. But defeats the point of having the spring-cloud-dependencies BOM.

Additionally should a Milestone release artifact even be in a final RELEASE BOM?

**Comment by ryanjbaxter** [comment]
See https://github.com/spring-cloud/spring-cloud-security/issues/172

No Milestones should not be included in releases.  We are adding checks to our release process to ensure it doesnt happen in the future.

**Comment by rohithn** [comment]
Hi, I am still facing this error. I've searched for fixes, but unable to find one. Could you please explain what I need to do in order to fix this now?

**Comment by spencergibb** [comment]
Use Greenwich.SR1

**Comment by rohithn** [comment]
Thank you. It resolved the issue of the dependency, but now I am getting this error:
`The bean 'oauth2ClientContext', defined in class path resource [org/springframework/boot/autoconfigure/security/oauth2/client/OAuth2RestOperationsConfiguration$SingletonScopedConfiguration.class], could not be registered. A bean with that name has already been defined in BeanDefinition defined in org.springframework.security.oauth2.config.annotation.web.configuration.OAuth2ClientConfiguration$OAuth2ClientContextConfiguration and overriding is disabled.`
Is this related?
