### ISSUE TITLE
Where is the document for Hoxton.M1?

### ISSUE THREAD

**Issue by eacdy** [spring-cloud/spring-cloud-release#171]
Where is the document for Hoxton.M1?
In
<https://spring.io/projects/spring-cloud#learn> 
I Cannot find any document for Hoxton.M1.

**Comment by ryanjbaxter** [comment]
It looks like the docs were never published, sorry about that.  We are in the process of releasing Hoxton.M2 today and I will make sure the docs are published and the page is updated.

**Comment by eacdy** [comment]
Thanks a lot.

**Comment by eacdy** [comment]
@ryanjbaxter Hi, I noticed that Hoxton.M2 has been released. But I Can still never find any document for Hoxton.

**Comment by marcingrzejszczak** [comment]
We're working on it. Stay tuned

**Comment by ryanjbaxter** [comment]
The docs are here https://cloud.spring.io/spring-cloud-static/Hoxton.M2/reference/html/spring-cloud.html

Sorry about the delay, we hit some snags in generating them.
