### ISSUE TITLE
When will Hoxton.M3 be available 

### ISSUE THREAD

**Issue by srivraokp** [spring-cloud/spring-cloud-release#175]
We are waiting for one of the fixes on springcloudgcp, can we get an update on when Hoxton.M3 will be available

**Comment by spencergibb** [comment]
Please watch https://github.com/spring-cloud/spring-cloud-release/milestones?direction=asc&sort=due_date&state=open

We today decided because of tight schedules, the delay on getting M3 out yesterday and working on spring one platform preparations, we moved it to Oct 3 based on boot 2.2.0.RC1.
