### ISSUE TITLE
Issues with Hoxton.RC2

### ISSUE THREAD

**Issue by octopus-prime** [spring-cloud/spring-cloud-release#177]
I use this for dependency-management
```
    dependencyManagement {
        imports {
            mavenBom("org.springframework.boot:spring-boot-dependencies:2.2.0.RELEASE")
            mavenBom("org.springframework.cloud:spring-cloud-dependencies:Hoxton.RC2")
        }
```

1) Since `Hoxton.RC2` I get these warnings
```
> Task :dependencyUpdates
Errors occurred while build effective model from /home/mike/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind/jaxb-osgi/2.2.10/c926a537af564ec047ec6308df1d0d2a03364a86/jaxb-osgi-2.2.10.pom:
    'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} in com.sun.xml.bind:jaxb-osgi:2.2.10
```
Note: I don't get these warnings with `Hoxton.RC1`

2) Since `Hoxton.RC2` I get a really old version of RestAssured
```
The following dependencies have later milestone versions:
 - io.rest-assured:rest-assured [3.3.0 -> 4.1.2]
     http://code.google.com/p/rest-assured
```
Note: I get version 4.1.1 if using `Hoxton.RC1`

**Comment by marcingrzejszczak** [comment]
Please use Boot 2.2.1 (https://github.com/spring-cloud/spring-cloud-release/blob/vHoxton.RC2/spring-cloud-starter-parent/pom.xml#L8) we also describe this in the documentation

**Comment by marcingrzejszczak** [comment]
Rest Assured version comes with Boot https://github.com/spring-projects/spring-boot/blob/v2.2.1.RELEASE/spring-boot-project/spring-boot-dependencies/pom.xml#L175

**Comment by octopus-prime** [comment]
I believe you are right.
The version 3.3.0 of RestAssured may come from spring-boot-test-autoconfigure.
See 'Compile Dependencies' in https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-test-autoconfigure/2.2.1.RELEASE

Nevertheless... by using Hoxton.RC1 I get version 4.1.1

Anyhow... I will override the version with `ext['rest-assured.version'] = '4.1.2'`

**Comment by marcingrzejszczak** [comment]
With Hoxton.RC1 you got a different one because it came from SC Contract BOM which was an issue. We removed it from the bom and now you get the one from Boot which you can override like you mentioned.
