### ISSUE TITLE
Hoxton.SR5 doc does not say it supports Spring Boot 2.3.x

### ISSUE THREAD

**Issue by longqinsi** [spring-cloud/spring-cloud-release#184]
In [the online documentation of Spring Cloud Hoxton.SR5](https://cloud.spring.io/spring-cloud-static/Hoxton.SR5/reference/html/), the supported Spring Boot Version is 2.2.1.RELEASE, but in a blog post [Spring Cloud Greenwich.SR6, Hoxton.SR5 and 2020.0.0-M2 (aka Ilford) are Available](https://spring.io/blog/2020/06/01/spring-cloud-greenwich-sr6-hoxton-sr5-and-2020-0-0-m2-aka-ilford-are-available), there is a statement "Hoxton.SR5 is compatible with both Spring Boot 2.3.x and 2.2.x". Please fix the bug in the online documentation.

**Comment by spencergibb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.

See https://github.com/spring-cloud/spring-cloud-release/wiki/Historical-Versions for the canonical source of cloud to boot mappings.
