### ISSUE TITLE
java-cfenv core library is managed by Hoxton.SR6

### ISSUE THREAD

**Issue by dyroberts** [spring-cloud/spring-cloud-release#186]
**Describe the bug**
Looks like the Hoxton.SR6 bom (maybe older SR too) is pinning an old version of java-cfenv core library (1.1.3.RELEASE), as well as java-cfenv-test-support library.
AFAICT it's coming from the spring-cloud-gcp-dependencies and spring-cloud-task-dependencies boms.

Is it expected that spring-cloud-dependencies would manage a module that is pivotal-cf org and `io.pivotal.*` group?
My guess is that it's not.

**Sample**
You can see this exposed here: https://github.com/dyroberts/test-java-cfenv-deps
Clone this example repo and run `./gradlew dependencies | grep java-cfenv` to see the latest version of the core java-cfenv library is being overridden by this older version from the Hoxton bom.

**Comment by spencergibb** [comment]
You need to open issues in each project to have them move that out of their `spring-cloud-*-dependencies` bom into the root pom of the project.

https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-dependencies/pom.xml

https://github.com/spring-cloud/spring-cloud-task/blob/master/spring-cloud-task-dependencies/pom.xml
