### ISSUE TITLE
Provide getting started with release trains mapping to Spring Boot generation

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-release#211]
I am working with the Wavefront team (Hi @shavidissa) on improving their getting started documentation for the Spring Boot starter. The starter has optional support for tracing via Sleuth so we need to tell users how they can include that in their existing project.

The [doc sandbox is here](http://docs-sandbox-b.wavefront.com/wavefront_springboot.html). We're considering reusing [this section of the project's page](https://spring.io/projects/spring-cloud#release-trains). 

I'd like as much as possible to not include too much information for existing projects. Each release announcement [has a section that describes how to get started](https://spring.io/blog/2020/08/04/spring-cloud-hoxton-sr7-has-been-released) for both Maven and Gradle.

Would it be possible to get a page somewhere that summarises all that, that is:

* Build instructions to get started
* Mapping between Spring Cloud release train and Spring Boot generation

In an ideal world, rather than the name of the release train, it would be very nice to get the actual version that we have to use (latest service release or milestone, depending on the situation).

Thanks!

**Comment by ryanjbaxter** [comment]
> Mapping between Spring Cloud release train and Spring Boot generation

This would be possible to retrieve programmatically using 
https://spring-cloud-info.cfapps.io/docs/spring-cloud-info.html#_spring_cloud_version_given_spring_boot_version

I wonder if we could make a page that would allow the user to either pick the Boot version or Cloud version and then automatically generate the Maven and Gradle getting started info.

Would that help @snicoll?

**Comment by snicoll** [comment]
> This would be possible to retrieve programmatically using
https://spring-cloud-info.cfapps.io/docs/spring-cloud-info.html#_spring_cloud_version_given_spring_boot_version

I had forgotten about that one!

> I wonder if we could make a page that would allow the user to either pick the Boot version or Cloud version and then automatically generate the Maven and Gradle getting started info.

Yeah that would be more than ideal of course!

**Comment by shavidissa** [comment]
Thank you, @snicoll and @ryanjbaxter!

> This would be possible to retrieve programmatically using
https://spring-cloud-info.cfapps.io/docs/spring-cloud-info.html#_spring_cloud_version_given_spring_boot_version

This is cool! I will use this :)

> I wonder if we could make a page that would allow the user to either pick the Boot version or Cloud version and then automatically generate the Maven and Gradle getting started info.

> Yeah that would be more than ideal of course!

This would be great for Spring Cloud and all the other dependencies in spring.io. It will make it easier for the user to get this info in one place. As Stéphane showed, I think this information is already captured in https://start.spring.io/actuator/info.

**Comment by ryanjbaxter** [comment]
@shavidissa 
> This is cool! I will use this :)

So does that get you what you need?  Or is there still missing information?

**Comment by snicoll** [comment]
@ryanjbaxter No. The endpoint doesn't provide what was requested in the original description, specifically

```
Would it be possible to get a page somewhere that summarises all that, that is:

* Build instructions to get started
* Mapping between Spring Cloud release train and Spring Boot generation
```

**Comment by ryanjbaxter** [comment]
@snicoll I have updated the page, please let me know what you think!

**Comment by snicoll** [comment]
Thanks @ryanjbaxter. Just to make sure I got this right, you mean https://spring.io/projects/spring-cloud#getting-started right?

**Comment by ryanjbaxter** [comment]
@snicoll yup!

**Comment by shavidissa** [comment]
Hi @ryanjbaxter,

Thanks a lot! This is much better and user friendly. We have it in our Wavefront docs :)

**Comment by snicoll** [comment]
Looks good indeed, I think this can be closed. Thanks a lot for the quick turnaround!

**Comment by ryanjbaxter** [comment]
Great thanks!
