### ISSUE TITLE
Release notes contain "111" and nothing else

### ISSUE THREAD

**Issue by maslano** [spring-cloud/spring-cloud-release#214]
**Describe the bug**
No release notes for Hoxton

**Sample**
https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-Hoxton-Release-Notes

**Comment by marcingrzejszczak** [comment]
Thanks - someone has deleted our wiki page. I've reverted it

**Comment by spencergibb** [comment]
And I've restricted access

**Comment by maslano** [comment]
thanks for a quick response
