### ISSUE TITLE
Typo in wiki Spring Cloud 2020.0 Release Notes

### ISSUE THREAD

**Issue by nallwhy** [spring-cloud/spring-cloud-release#221]
in [Spring Cloud 2020.0 Release Notes](https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes)

AS-IS

### Renamed Starters

| Old Starter      | Renamed Starter |
| ---------------- | --------------- |
| spring-cloud-starter-kubernetes      | spring-cloud-kubernetes-fabric8       |

TO-BE

### Renamed Starters

| Old Starter      | Renamed Starter |
| ---------------- | --------------- |
| spring-cloud-starter-kubernetes      | spring-cloud-starter-kubernetes-fabric8       |

**Comment by ryanjbaxter** [comment]
Fixed, thanks!
