### ISSUE TITLE
Message body at subscriber is EMPTY with spring cloud 2020.0.1 and 2020.0.2

### ISSUE THREAD

**Issue by venkataklagisetty** [spring-cloud/spring-cloud-release#223]
**Describe the bug**
Spring boot 2.4.3 and apache camel 3.7.3
Spring cloud version 2020.0.2  and 2020.0.1
When a message is published to a topic, at subscriber level, the BODY is empty or body from exchange is {} ,but header looks good.  
When I switched to spring cloud 2020.0.0 it started working.

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by spencergibb** [comment]
What project are you using? Spring cloud stream?

**Comment by venkataklagisetty** [comment]
spring-cloud-dependencies

**Comment by spencergibb** [comment]
No, that's no specific enough. What other spring cloud project are you using?

**Comment by venkataklagisetty** [comment]
Those are the spring cloud projects I am using. Nothing else added for spring cloud.
I have camel and other dependencies added in it.

**Comment by spencergibb** [comment]
Then I don't know how to help you. This project contains only pom.xml files with references to other spring cloud projects.
