### ISSUE TITLE
fallback is not effective in springboot 2.4.1

### ISSUE THREAD

**Issue by zth1993** [spring-cloud/spring-cloud-release#224]
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by spencergibb** [comment]
There's not even enough to transfer to the right repo. If it's spring cloud circuit breaker, Netflix or gateway open an issue in the right repo with the information requested
