### ISSUE TITLE
Spring Cloud 2020.0.3 doesn't contain Spring Cloud Security

### ISSUE THREAD

**Issue by PonomarevMM** [spring-cloud/spring-cloud-release#225]
spring cloud security was in spring cloud 2020.0.0-RC1, but I don't see it in spring cloud 2020.3
is there any announcement regarding spring cloud security? Is it planned to stay in spring cloud?
Any official way to migrate (in case if no support of spring cloud security), especially for oauth2 related stuff (personally interested in spring-cloud-starter-oauth2) ?

**Comment by PonomarevMM** [comment]
found some information here: https://spring.io/blog/2020/12/22/spring-cloud-2020-0-0-aka-ilford-is-available

**Comment by spencergibb** [comment]
Reopening to note in the release notes
