### ISSUE TITLE
When will Hoxton.SR12 release?

### ISSUE THREAD

**Issue by HaojunRen** [spring-cloud/spring-cloud-release#227]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by spencergibb** [comment]
Early next week

**Comment by jonatan-ivanov** [comment]
@HaojunRen Next time could you please ask questions like this on our gitter channel (https://gitter.im/spring-cloud/home) or on Twitter?

**Comment by HaojunRen** [comment]
Hoxton.SR12 is Released, but it seems spring-cloud-openfeign-dependencies 2.2.9.RELEASE is missing?

![图片](https://user-images.githubusercontent.com/42354711/124776565-21b97480-df72-11eb-9b60-1b4fb7150e33.png)

**Comment by spencergibb** [comment]
Working thru some issues.
