### ISSUE TITLE
Would it be a good idea to make a spring-cloud-gradle-plugin?

### ISSUE THREAD

**Issue by sixcorners** [spring-cloud/spring-cloud-release#228]
**Is your feature request related to a problem? Please describe.**
I wish there was a spring-cloud-starter-parent equivalent on the gradle side.

**Describe the solution you'd like**
There could be a spring-cloud-gradle-plugin that sets up the spring-cloud-dependencies and brings in the correct spring-boot-gradle-plugin version.

**Describe alternatives you've considered**
I could just continue to set both versions and make sure to check the docs to make sure they are compatible with each other.

**Comment by spencergibb** [comment]
No. We let the spring boot plugin handle all of that

**Comment by sixcorners** [comment]
Is there a way to specify the spring cloud version and let the spring boot version be brought in transitively?

**Comment by spencergibb** [comment]
No, you have to specify both versions

**Comment by jameswynn** [comment]
You can pretty easily create a gradle plugin that does this. I use one (sadly not FOSS) that wires in all the spring boot and spring cloud bits. It's very handy for managing a fleet of microservices. But I agree that such functionality is outside the scope of Spring Cloud itself.
