### ISSUE TITLE
Update release notes documentation

### ISSUE THREAD

**Issue by ahunigel** [spring-cloud/spring-cloud-release#232]
**Describe the bug**
No information about 2020.0.4

**Sample**
https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#202004
