### ISSUE TITLE
[Docs] Missing Spring Boot compatibility guide for Spring Cloud 2021 serial in https://spring.io/projects/spring-cloud

### ISSUE THREAD

**Issue by DevDengChao** [spring-cloud/spring-cloud-release#233]
In document https://spring.io/projects/spring-cloud#adding-spring-cloud-to-an-existing-spring-boot-application 's `Table 1. Release train Spring Boot compatibility` section, there is no guiding for Spring Cloud 2021 serial is compatable with which version of Spring Boot like other Spring Cloud serials:

![image](https://user-images.githubusercontent.com/16363180/145526099-65d90331-c6ca-4d84-877d-c1a10fa6c788.png)

Ps: I found the compatiable Spring Boot version later in https://docs.spring.io/spring-cloud/docs/2021.0.0/reference/html/ .

Reference:
+ [The previous issue I submitted at spring-projects/spring-boot which redirected me to here](https://github.com/spring-projects/spring-boot/issues/28968)

**Comment by ryanjbaxter** [comment]
Should be fixed now, thanks
