### ISSUE TITLE
spring-cloud-dependencies maven metadata doesn't include 2020.X releases above 2020.0.1

### ISSUE THREAD

**Issue by ssthom** [spring-cloud/spring-cloud-release#234]
# Bug report

The latest spring-cloud-dependencies maven metadata in Maven central does not include releases above 2020.0.1 (2020.0.2, 2020.0.3, 2020.0.4). We use Gradle dynamic versions 2020.0.+ in order to pull in the latest patch version. But recently our builds started breaking because instead of pulling in 2020.0.4 Gradle is pulling in 2020.0.1.

https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/maven-metadata.xml
```xml
<versions>
    ...
    <version>2020.0.0</version>
    <version>2020.0.1</version>
    <version>2021.0.0</version>
</versions>
```

Gradle Dependency tree:
```
+--- org.springframework.cloud:spring-cloud-dependencies:2020.0.+ -> 2020.0.1
|    +--- org.springframework.cloud:spring-cloud-starter:3.0.1 (c)
|    +--- org.springframework.cloud:spring-cloud-context:3.0.1 (c)
|    +--- org.springframework.cloud:spring-cloud-commons:3.0.1 (c)
|    \--- org.springframework.security:spring-security-rsa:1.0.9.RELEASE (c)
```

**Comment by spencergibb** [comment]
Duplicates https://github.com/spring-cloud/spring-cloud-build/issues/223
