### ISSUE TITLE
Will there be another Hoxton release?

### ISSUE THREAD

**Issue by devoxel** [spring-cloud/spring-cloud-release#235]
Hi - wondering if there's any plans for another Hoxton release. Right now Spinnaker is still on Hoxton, and [this fix](https://github.com/spring-cloud/spring-cloud-config/pull/1597/files) would be useful to backport, since it prevents using things like GCS buckets for config.

If there isn't one planned that's fine - it would just be useful if there was - I could backport that fix.

Either way, thanks for reading,
~ devoxel

**Comment by jonatan-ivanov** [comment]
Hoxton reached EOL in 2020-11-26, see the support terms here: https://spring.io/projects/spring-cloud-config#support
