### ISSUE TITLE
Where can I view the official documentation for Spring Cloud Greenwich.SR6?

### ISSUE THREAD

**Issue by zq99299** [spring-cloud/spring-cloud-release#236]
Where can I view the official documentation for Spring Cloud Greenwich.SR6?

I can't find the historical documentation in spring.io anymore, what should I do?

**Comment by spencergibb** [comment]
SR6 never got docs https://cloud.spring.io/spring-cloud-static/Greenwich.SR5/

**Comment by zq99299** [comment]
> SR6 从来没有文档https://cloud.spring.io/spring-cloud-static/Greenwich.SR5/
Thank you for your help, it was very useful for me
