### ISSUE TITLE
Spring cloud 2020.0.6 is not present in https://spring.io/projects/spring-cloud#learn

### ISSUE THREAD

**Issue by DevDengChao** [spring-cloud/spring-cloud-release#246]
![image](https://user-images.githubusercontent.com/16363180/178712510-42c667de-2619-41ce-b424-57cbf98e36ba.png)

Sorry I didn't found the repository for https://spring.io, so I created the issue here.

**Comment by marcingrzejszczak** [comment]
Fixed! Thanks!
