### ISSUE TITLE
Version 2021.0.4 not available in maven central

### ISSUE THREAD

**Issue by jensvancauwenberge** [spring-cloud/spring-cloud-release#247]
**Describe the bug**
Version 2021.0.4 was released 2 days ago: https://github.com/spring-cloud/spring-cloud-release/releases/tag/v2021.0.4
In maven central, the last version for 2021.0.x is still pointing to 2021.0.3: https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-dependencies/

**Comment by ryanjbaxter** [comment]
We hit a bit of a snag late last week with the release, the artifacts will be posted this week at some point.  Keep an eye on the Spring Blog for the release announcement
https://spring.io/blog
