### ISSUE TITLE
Documentation :: Remove deprecated Spring Cloud Cluster from spring.io/projects/spring-cloud

### ISSUE THREAD

**Issue by pguti778** [spring-cloud/spring-cloud-release#248]
As per [Spring Cloud Cluster repo](https://github.com/spring-attic/spring-cloud-cluster#spring-cloud-cluster-is-no-longer-actively-maintained-by-vmware-inc), this project is archived. 

Please update the documentation and remove all references to it. More than happy to help on updating the documentation.

**Comment by ryanjbaxter** [comment]
What documentation are you referring to?

**Comment by pguti778** [comment]
I'm referring to remove the reference from both here [https://spring.io/projects/spring-cloud](https://spring.io/projects/spring-cloud)  and from here [https://spring.io/projects/spring-cloud-cluster](https://spring.io/projects/spring-cloud-cluster)
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/71953686/191353542-969968c5-049e-4fb6-9c08-2686a3cb75c3.png">

**Comment by ryanjbaxter** [comment]
Thanks I have removed it
