### ISSUE TITLE
Documentation for 2022.0.0-RC3 is gone, 2022.0.0 missing, 2021.0.5 doc links lead to 2022.0.0

### ISSUE THREAD

**Issue by DuncanCasteleyn** [spring-cloud/spring-cloud-release#256]
**Describe the bug**
On https://spring.io/projects/spring-cloud#learn
- The documentation of 2022.0.0-RC3 is gone
- The latest version is not yet set to 2022.0.0 and is missing from the version list
- The link of the documentation of 2021.0.5 leads to the documentation of 2022.0.0

**Comment by ryanjbaxter** [comment]
Fixes now, thanks
