### ISSUE TITLE
Spring Cloud Dependencies

### ISSUE THREAD

**Issue by Doctor-Vee** [spring-cloud/spring-cloud-release#257]
Hi Spring Cloud Team,

I'm Victor from Reloadly.

We're currently migrating our projects and services to Java 17 and Spring Boot 3.0 but we're having issues with Spring Cloud Dependencies. 

We have tried using the 2022.0.0-RC3 version but it doesn't work for us.

Please, when are you likely to release the next GA version?

**Comment by spencergibb** [comment]
2022.0.0 was released on Dec 17

**Comment by Doctor-Vee** [comment]
Oh ... sorry ... my bad ... I just discovered that ... shortly before your comment came in.
Thanks.
