### ISSUE TITLE
trace information lost after spring cloud 2021.0.6 update 

### ISSUE THREAD

**Issue by oemergenc** [spring-cloud/spring-cloud-release#259]
**Describe the bug**
We experience a problem with our trace information after updating to spring cloud 2021.0.6.
We are using spring-cloud-gcp-logging for trace information and after the update to spring cloud 2021.0.6 we are losing the trace information for some logs.

**Sample**
I have created a very simple test application, see here:
https://github.com/oemergenc/spring-cloud-tracing-problem

There are two branches: main branch uses spring cloud 2021.0.5 and the broken branch uses 2021.0.6. There is also a very simple test which runs successfully on the main branch and fails on the broken branch. It would be nice if you could have look at this, since I have no idea where trace information is lost. The test is here:

https://github.com/oemergenc/spring-cloud-tracing-problem/blob/main/src/test/java/com/example/tracing/problem/tracing/ReactiveLoggingIntegrationTest.java

Thanks in advance

**Comment by marcingrzejszczak** [comment]
I think you should file this issue in the GCP project. Definitely spring-cloud-release is not the place for this issue.
