### ISSUE TITLE
Spring Cloud 2021.0.6 not listed on https://spring.io/projects/spring-cloud#learn

### ISSUE THREAD

**Issue by tsmgodoi** [spring-cloud/spring-cloud-release#260]
**Is your feature request related to a problem? Please describe.**
Is the Spring Cloud 2021.0.6 really released? It's not listed on https://spring.io/projects/spring-cloud#learn. Can we use it already for production?

**Describe the solution you'd like**
I would like to know if a release is publish here on GitHub, but not listed on https://spring.io/projects/spring-cloud#learn, can already be used or not.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Thank you!

**Comment by spencergibb** [comment]
This is fixed

<img width="734" alt="image" src="https://user-images.githubusercontent.com/594085/228084535-5de4f330-14be-4ed4-8a4b-b1de9a6162e1.png">
