### ISSUE TITLE
Spring Boot [3.1.0] is not compatible with this Spring Cloud release train

### ISSUE THREAD

**Issue by jesperancinha** [spring-cloud/spring-cloud-release#261]
**Describe the bug**
It appears Spring Boot 3.1.0 breaks the latest version of spring-cloud-dependencies. In my project [staco](https://github.com/jesperancinha/staco-app/pull/1874), I'm reproducing this problem in the containers.

**Sample**
2023-05-21T13:05:08.348Z ERROR 7 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Your project setup is incompatible with our requirements due to following reasons:

- Spring Boot [3.1.0] is not compatible with this Spring Cloud release train

Action:

Consider applying the following actions:

- Change Spring Boot version to one of the following versions [3.0.x] .
You can find the latest Spring Boot versions here [https://spring.io/projects/spring-boot#learn].

**Comment by spencergibb** [comment]
Our release is next week
