### ISSUE TITLE
Can you release 2022.0.3 version please

### ISSUE THREAD

**Issue by ouaibsky** [spring-cloud/spring-cloud-release#262]
**Describe the bug**
2022.0.X contains a huge regression since latest 2021.0.X
With 2022 version you cannot used anymore a CompositeDiscoveryClient with a KubernetesInformerDiscoveryClient.
that has been fixed into this commit: https://github.com/spring-cloud/spring-cloud-kubernetes/commit/d9c458347dcf38b1d3cc701cb4968ee0061de69c

The previous code was using List.of(...) with value coming from serviceLister that can be null and obviously it's not possible with factory List.of() leading to NPE.

2022.0.x contains also mandatory features like being able to discover pod the HTTPS connecto.

Thx
Christophe (aka ouaibsky)

**Sample**

**Comment by spencergibb** [comment]
Duplicates #261

**Comment by spencergibb** [comment]
see https://github.com/spring-cloud/spring-cloud-release/issues/261#issuecomment-1556205506. We are in the middle of the release proccess
