### ISSUE TITLE
Add link to Spring Cloud github org

### ISSUE THREAD

**Issue by knlkshyp** [spring-cloud/spring-cloud-release#268]
On [Spring Cloud](https://docs.spring.io/spring-cloud/docs/current/reference/html/documentation-overview.html#documentation) reference documentation for version **2022.0.3** where the text _"get involved"_ is just a plain text.

Please refer the image below
<img width="1440" alt="spring-cloud-repo-missing-hyperlink" src="https://github.com/spring-cloud/spring-cloud-release/assets/15921119/d35c8843-55f4-492a-9b8a-90b4452a585d">

But on [Spring Boot](https://docs.spring.io/spring-boot/docs/3.2.0-SNAPSHOT/reference/htmlsingle/]) reference documentation page for version **3.2.0-SNAPSHOT**, there is a hyperlink on text _"get involved"_ which takes the user to github repository for Spring Boot project.

Please refer the image below
<img width="1440" alt="spring-boot-repo-hyperlink" src="https://github.com/spring-cloud/spring-cloud-release/assets/15921119/025ebd6d-cbd1-443d-9ee0-b7fc913a5e99">

I hope this behaviour should be consistent across the documentation for all Spring projects.

**Comment by spencergibb** [comment]
There's no individual project to link to like Spring Boot. The closest would be https://github.com/spring-cloud.

The source for that line is https://github.com/spring-cloud/spring-cloud-release/blob/2c6c3bd11a52d3c7bf81b8283e27450129a9fc7b/train-docs/src/main/resources/templates/spring-cloud/documentation-overview.hbs#L38

PRs welcome.

**Comment by knlkshyp** [comment]
@pivotal-cla This is an Obvious Fix

PR raised #269
