### ISSUE TITLE
what is the plan to release spring cloud compatibile for springboot 3.1.x

### ISSUE THREAD

**Issue by rajanigk** [spring-cloud/spring-cloud-release#270]
current release of spring cloud support is based on spring boot 3.0.x. 3.0.x is not the LTS release and it as well has security bugs
which are fixed in 3.1.x. 
Without spring cloud giving a release train to support springboot 3.1.x we are unable to move the LTS release of springboot  3.1.x. So would like to know the release plan of spring cloud to support springboot 3.1.x.

**Comment by marcingrzejszczak** [comment]
We support Boot 3.1 starting from 2022.0.3 https://spring.io/blog/2023/05/25/spring-cloud-2022-0-3-aka-kilburn-is-available
