### ISSUE TITLE
Rsocket and Websocket in Webflux mode on the Spring Cloud

### ISSUE THREAD

**Issue by kasra-haghpanah** [spring-cloud/spring-cloud-release#272]
In my opinion, at the moment, one of the weaknesses of the Spring framework is the failure to finish Rsocket and Websocket in Webflux mode for Spring-cloud-gateway, even making a message broker that supports Rsocket and Reactive HTTP at the same time. In addition to adding these affairs, adding general maps automatically like Redis for keeping Websocket or Rsocket sessions easily helps developers broadcast data across these sessions through multiple machines.

**Comment by spencergibb** [comment]
Closing in favor of transferred issue https://github.com/spring-cloud/spring-cloud-gateway/issues/3053. Please don't open the same issue multiple times
