### ISSUE TITLE
Compatible with Spring Boot 3.2.x

### ISSUE THREAD

**Issue by flinden68** [spring-cloud/spring-cloud-release#274]
When will there be a release of Spring Cloud which is compatible with Spring Boot 3.2.x

**Comment by spencergibb** [comment]
See https://github.com/spring-cloud/spring-cloud-release/milestones?direction=asc&sort=due_date&state=open

**Comment by sergey-morenets** [comment]
Hi @spencergibb 

Spring Cloud 2023.0.0 should have been released yesterday but I didn't see any release notes. Was it delayed by some reason?

**Comment by spencergibb** [comment]
It's in progress

**Comment by fede843** [comment]
call me anxious, but I am waiting too :)

**Comment by wangliang181230** [comment]
Waiting, waiting, wait...ing, w.........ZZZzzz.

**Comment by sergey-morenets** [comment]
> It's in progress

Thank you for the quick answer. Do you have ETA for 2023 release?

**Comment by martijndebruijn** [comment]
Why are the release dates of Spring Cloud not synced with the release dates
of Spring Boot?

Op wo 6 dec. 2023 13:08 schreef Sergiy Morenets ***@***.***>:

**Comment by sergey-morenets** [comment]
@martijndebruijn That's a perfect question. Spring Boot was released more than 2 weeks ago.

**Comment by Saljack** [comment]
@martijndebruijn There is a simple answer because Spring Cloud uses Spring Boot. It is the same as Spring Framework is released before Spring Boot. So it is always Spring Framework, Spring Data, Spring Boot and Spring Cloud in dependency order.
