### ISSUE TITLE
Spring Cloud compatibility with Spring Boot 3.2.x

### ISSUE THREAD

**Issue by bschlapsi4tf** [spring-cloud/spring-cloud-release#276]
The Spring Cloud documentation page does not include the latest Spring Boot version 3.2.x
https://spring.io/projects/spring-cloud
![image](https://github.com/spring-cloud/spring-cloud-release/assets/147731209/8f0bf6c5-9eac-4416-99a9-ece7b4270f89)

Is Spring Cloud 2022.0.x aka Kilburn compatible with Spring Boot 3.2.x? 
If not when will the new Spring Cloud 2023.0.x be released, because Spring Boot 3.2 was already released on 2023-11-23

**Comment by herodotus-cloud** [comment]
> The Spring Cloud documentation page does not include the latest Spring Boot version 3.2.x https://spring.io/projects/spring-cloud ![image](https://private-user-images.githubusercontent.com/147731209/288366690-8f0bf6c5-9eac-4416-99a9-ece7b4270f89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTgwNDcsIm5iZiI6MTcwMTg1Nzc0NywicGF0aCI6Ii8xNDc3MzEyMDkvMjg4MzY2NjkwLThmMGJmNmM1LTllYWMtNDQxNi05OWE5LWVjZTdiNDI3MGY4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQxMDE1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmE0ZDU3ZDc2Nzc5MWQ2NjgzODQ5ZjI4NWYwYmU5MDg0MzQ4YWMxZjY4NjgzMjFlM2I5Y2Y5MzVhOGNkZjNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R20dXrkTzuKmXZ3GMEuNPOe9e934aSam6sxZseQNUts)
> 
> Is Spring Cloud 2022.0.x aka Kilburn compatible with Spring Boot 3.2.x? If not when will the new Spring Cloud 2023.0.x be released, because Spring Boot 3.2 was already released on 2023-11-23

See #274
