### ISSUE TITLE
When will Spring Cloud 2023.0.0 be deployed to public center repository?

### ISSUE THREAD

**Issue by honhimW** [spring-cloud/spring-cloud-release#277]
**First of all, thank you for your work.**

I noticed that the Spring Cloud 2023.0.0 version has been released, but it seems that I can’t find it in the Maven Central Repository.
[https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2023.0-Release-Notes](url)

**Comment by spencergibb** [comment]
It is there. Searching requires an index update.

**Comment by honhimW** [comment]
Nice!😃

**Comment by sergey-morenets** [comment]
Hi @spencergibb 

Thanks for the release but have you updated the documentation? I opened the projects page: https://spring.io/projects/spring-cloud#learn

and still saw 2022.0.4 as current version:

`2022.0.4 CURRENT GA`

and when I opened the docs page: https://docs.spring.io/spring-cloud/docs/current/reference/html/

I see that versions are out-of-date:

```
Release Train Version: 2022.0.4

Supported Boot Version: 3.0.9
```

**Comment by spencergibb** [comment]
Yeah, we've had a glitch with the documentation
