### ISSUE TITLE
Create release tag in GitHub

### ISSUE THREAD

**Issue by zambrovski** [spring-cloud/spring-cloud-release#278]
**Describe the bug**

I received a dependabot notification about the 2023.0.0 release (so the artifact is available in Maven Central) and the https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2023.0-Release-Notes is available too.

In the same time, the GitHub Release seems to be not available: https://github.com/spring-cloud/spring-cloud-release/releases

This leads to a confusion, because the release notes in the dependabot are not available:

![image](https://github.com/spring-cloud/spring-cloud-release/assets/673128/d66611fd-042b-4427-8140-74cde249fea9)

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-release/releases/tag/v2023.0.0
