### ISSUE TITLE
Why spring cloud release 2023.0.1 is missing?

### ISSUE THREAD

**Issue by jamerlan** [spring-cloud/spring-cloud-release#283]
https://github.com/spring-cloud/spring-cloud-release/releases

in releases list 2023.0.1 is missing
it is confusing for people who watch this page for new releases

is it possible to add 2023.0.1 to the list? (I see it is present in tags.. but tags are not releases)

**Comment by ryanjbaxter** [comment]
Sorry about that
https://github.com/spring-cloud/spring-cloud-release/releases/tag/v2023.0.1

**Comment by mdiskin** [comment]
Looks like v2023.0.2 might be also missing

**Comment by cppwfs** [comment]
@mdiskin Thank you for the heads up.   It is now available https://github.com/spring-cloud/spring-cloud-release/releases/tag/v2023.0.2

**Comment by mdiskin** [comment]
@cppwfs the "current" docs are pointing to older releases e.g. 4.0.5 https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_spring_cloud_config_server

**Comment by spencergibb** [comment]
The current links are here which are correct https://spring.io/projects/spring-cloud-config#learn
