### ISSUE TITLE
 Spring Cloud compatibility with Spring Boot 3.3.x

### ISSUE THREAD

**Issue by DRoppelt** [spring-cloud/spring-cloud-release#286]
**Is your feature request related to a problem? Please describe.**
Spring Boot 3.3.0 released last week (https://github.com/spring-projects/spring-boot/releases/tag/v3.3.0)

Is the latest Spring Cloud iteration compatible with 3.3.0 or will there be an update in 2023.X.Y / 24.0.0?

**Describe the solution you'd like**
update docs that state 3.3.X compatibilty or a plan to add them to a future release

**Additional context**
compatibility matrix posted here does not state 3.3.0 compatibility https://spring.io/projects/spring-cloud

**Comment by spencergibb** [comment]
See https://github.com/spring-cloud/spring-cloud-release/milestones

**Comment by DRoppelt** [comment]
So starting with `2023.0.2`, it will officially support 3.3.0? Gotcha

**Comment by barbetb** [comment]
Was the release cancelled? It's 4 days due?

**Comment by spencergibb** [comment]
https://x.com/springcloud/status/1796579430652944780

**Comment by spencergibb** [comment]
@abccbaandy that has been updated, thanks
