### ISSUE TITLE
Null fields in proxies after upgrading to Spring Cloud 2023.0.2 and Spring Boot 3.3.1

### ISSUE THREAD

**Issue by mgaceanu** [spring-cloud/spring-cloud-release#289]
I don't know if this is the right repo for this bug report. Anyway, here it goes: 

**Describe the bug**
I have an integration test that fails after upgrading to Spring Cloud 2023.0.2 and Spring Boot 3.3.1. All goes well if I revert and use 2022.0.5 / 3.0.4

The code is testing the fallback of a `@Retry` annotated method.
While debugging the code it seems the autowired fields are null.

```
    @Retry(name = "retryApi", fallbackMethod = "fallbackAfterRetry")
    public String retryApi(@NotNull String param) {
        return someBean.doThis();
    }

    private String fallbackAfterRetry(String param, Exception ex) {
        fallbackBean.doThat();
        return "all retries have exhausted";
    }
```

and the test:
```
    @Test
    void retryApi() {
        Mockito.doThrow(new RuntimeException("Test exception"))
               .when(someBean)
               .doThis();

        service.retryApi("asd");

        // verify fallback
        Mockito.verify(fallbackBean).doThat();
    }
```

**Sample**
I'm attaching a sample application.
[spring-cloud-sample.zip](https://github.com/user-attachments/files/15952751/spring-cloud-sample.zip)

Thanks,
Mircea

**Comment by ryanjbaxter** [comment]
Other than having spring-cloud-openfeign on the classpath I don't even see you really using Spring Cloud.  Does the problem also exist without Spring Cloud on the classpath?

**Comment by mgaceanu** [comment]
Thanks for the feedback. It's indeed not related to Spring Cloud and I'll close the issue.
If anybody else stumbles upon this, the issue was occurring in resilience4j 2.1.0, but not anymore with 2.2.0
Cheers
