### ISSUE TITLE
Releases page is not updated every time

### ISSUE THREAD

**Issue by jamerlan** [spring-cloud/spring-cloud-release#291]
We have a release page https://github.com/spring-cloud/spring-cloud-release/releases
Currently it contains [v2023.0.2](https://github.com/spring-cloud/spring-cloud-release/releases/tag/v2023.0.2)
but v2023.0.3 is available

release page was not updated.. The same thing happened with 2 previous releases. Please fix that and update release instructions to keep that page up-to-date

**Comment by ryanjbaxter** [comment]
We are doing the best we can with the current workload and people we have.  Appreciate the heads up and I have created the release.
https://github.com/spring-cloud/spring-cloud-release/releases/tag/v2023.0.3
