### ISSUE TITLE
stream bridge consumer class not consuming on 2023.0.3

### ISSUE THREAD

**Issue by SanzarRehman** [spring-cloud/spring-cloud-release#292]
**Describe the bug**
Serialization is not working on 2023.0.3 ,  same code working on 2023.0.2

**Sample**
Getting this error 

stream bridge consumer class [B cannot be cast to class com.b.notificatoin.client.SmsNotification ([B is in module java.base of loader 'bootstrap'; com.b.notificatoin.client.SmsNotification is in unnamed module of loader 'app')

` @Bean
  public Consumer<SmsNotification> sms() {
    return sms -> {
      log.debug("[SMS Consumer]: " + sms.getKey());
    };
  }`

**Comment by ryanjbaxter** [comment]
Please don't open multiple issues on the same topic
https://github.com/spring-cloud/spring-cloud-stream/issues/2993
