### ISSUE TITLE
Availability of the current version 2022.x

### ISSUE THREAD

**Issue by s3kae** [spring-cloud/spring-cloud-release#294]
Is it possible to publish the current releases of version 2022.x in the Maven repositories as well? Unfortunately, only up to version 2022.05 is available. The versions 2022.07 and 2022.08 are missing. 
check:
- [mvnrepository](https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-dependencies)
- [maven central](https://central.sonatype.com/artifact/org.springframework.cloud/spring-cloud-dependencies/versions)

**Comment by ryanjbaxter** [comment]
Any releases after 2022.0.5 in the 2022.0.x release train are for commercial customers only and are only available in a private repository.
