### ISSUE TITLE
Spring Cloud Release 2024.0.0 (Moorgate) ? 

### ISSUE THREAD

**Issue by alibutt30** [spring-cloud/spring-cloud-release#296]
Hello Spring team, 

There was a milestone for Spring cloud release 2024.0.0 (a.k.a Moorgate) planned for yesterday (02-December-2024) but it was not released. 
Just wanted to ask if the timeline has been moved forward ? 

Thank you so much,

**Comment by spencergibb** [comment]
It is in progress

**Comment by alibutt30** [comment]
Thank you so much for the update @spencergibb
