### ISSUE TITLE
Spring cloud release 2024.0.0 on 02-December-2024

### ISSUE THREAD

**Issue by aspix** [spring-cloud/spring-cloud-release#298]
Hello Spring team,

I saw in the Spring release calendar that on 02-December-2024 there should be a release for Spring cloud release 2024.0.0 (Moorgate). I don't find it yet today on 04-December. 

Do you know when it will be released?

Kr
Jos

**Comment by rohan-changejar** [comment]
Hello spring team, 
Any updates on the 2024.0.0 release?

**Comment by hbingen** [comment]
My project gets failed merge requests from renovate because the 2024 release does not exists in github yet. Any news on when it will be available on github?

**Comment by aspix** [comment]
Indeed. My build is working now. It's not yet on the website or mvnrepository.com, but it should arrive there.
Thank you!

**Comment by rohan-changejar** [comment]
Great, thanks for the quick reply.
