### ISSUE TITLE
every time new release on github "releases" page is missing

### ISSUE THREAD

**Issue by jamerlan** [spring-cloud/spring-cloud-release#299]
Take a look at releases page: https://github.com/spring-cloud/spring-cloud-release/releases

it shows that latest release is v2023.0.3
but actually release v2023.0.4 is available

and it happens over and over again: https://github.com/spring-cloud/spring-cloud-release/issues/283

so I suggest to modify release checklist and add one more step: describe new release on github too

**Comment by spencergibb** [comment]
Done
