### ISSUE TITLE
Spring cloud dependency requires Maven 3.3

### ISSUE THREAD

**Issue by JagmohanSharma** [spring-cloud/spring-cloud-release#56]
We have spring boot application which have spring cloud hystrix dependencies. we are able to build it using mvn clean install at our local. we are using these dependencies--- 
```
   <dependency>
           <groupId>org.springframework.cloud</groupId>
          <artifactId>spring-cloud-starter-config</artifactId>
     </dependency>
        <dependency>
          <groupId>com.netflix.hystrix</groupId>
            <artifactId>hystrix-javanica</artifactId>
           </dependency>
           <dependency>
          <groupId>org.springframework.cloud</groupId>
             <artifactId>spring-cloud-starter-hystrix</artifactId>
             </dependency>
           <dependency>
            <groupId>org.springframework.cloud</groupId>
             <artifactId>spring-cloud-starter-hystrix-dashboard</artifactId>
              </dependency>
           <dependency>
           <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-turbine</artifactId>
              </dependency>
```

however its working fine on local but build is failing on bamboo  with following message.
“Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.0.2:sonar
 (default-cli) on project open-platform-boot-parent: For artifact {org.springframework:spring-core:null:jar}: The version cannot be empty. -> [Help 1]”.

Whenever we add spring cloud dependency , it causes this bamboo build failure. We are not able to detect the cause for this. 

We later on injected spring cloud dependencies individually as well---

                 <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-context</artifactId>
                <version>${spring.cloud.hystrix.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-commons</artifactId>
                <version>${spring.cloud.hystrix.version}</version>
            </dependency>

            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-netflix-core</artifactId>
                    <version>${spring.cloud.hystrix.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-starter-archaius</artifactId>
                    <version>${spring.cloud.hystrix.version}</version>
            </dependency>
            <dependency>
                <groupId>com.netflix.hystrix</groupId>
                <artifactId>hystrix-core</artifactId>
                    <version>${hystrix.netflix.version}</version>
            </dependency>
            <dependency>
                <groupId>com.netflix.hystrix</groupId>
                <artifactId>hystrix-metrics-event-stream</artifactId>
                    <version>${hystrix.netflix.version}</version>
            </dependency>
            <dependency>
                <groupId>com.netflix.hystrix</groupId>
                <artifactId>hystrix-javanica</artifactId>
                <version>${hystrix.netflix.version}</version>
            </dependency>

But this got failed on bamboo build with same error:
 “Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.0.2:sonar
(default-cli) on project open-platform-boot-parent: For artifact {org.springframework:spring-core:null:jar}:
 The version cannot be empty. -> [Help 1]”.

we have tried with exluding spring core and spring boot dependency from these. but got same error. 

kindly help in this regard as this is bit urgent for us to build this.

**Comment by spencergibb** [comment]
Sounds like there's a problem with your bamboo build, if you can build it locally.

**Comment by JagmohanSharma** [comment]
Actually when we add spring cloud dependencies then only bamboo build gets failed with error 
“Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.0.2:sonar
(default-cli) on project open-platform-boot-parent: For artifact {org.springframework:spring-core:null:jar}:
The version cannot be empty. -> [Help 1]”.

Do we have any conflict between spring boot and spring cloud for any particular dependency version?

**Comment by spencergibb** [comment]
Without seeing your project I can't say what is wrong. Spring Cloud gets its spring dependencies from spring boot. Again, if it works locally, what can we do?

**Comment by JagmohanSharma** [comment]
I found the reason for this, Actually this is causing because of maven version 3.2.3 as today we updated the maven version at our local. So this is getting failed due to this. Same version is also being used on bamboo. Can you please assist as what is the main cause of conflict with maven version?

**Comment by spencergibb** [comment]
We require maven [3.3.x](https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/docs/src/main/asciidoc/building-base.adoc), currently 3.3.9 (though it's not mentioned in this readme) using the provided maven wrapper `./mvnw`.

**Comment by JagmohanSharma** [comment]
Thank you for helping us in resolving this issue. As now with latest maven version 3.3.9 we are able to build this. :)

**Comment by JagmohanSharma** [comment]
I have one doubt here. As is there any workaorund to make it build successfully with maven version 3.2.3. Or you mean to say it will not work with at all without 3.3.x maven version???

**Comment by shakuzen** [comment]
@JagmohanSharma If you build using the Maven wrapper `./mvnw` (on Linux/OSX) or `mvn.cmd` (on Windows) instead of `mvn` then you do not need to worry about the version of Maven as it will use the correct version for this project (downloading it if need be). Build tool wrappers are for exactly this reason of avoiding builds that behave differently on different setups. This project defines the version of Maven that works for it in its wrapper config, so as long as you use the wrapper you can expect it to work.

**Comment by JagmohanSharma** [comment]
Okk I will try in this way as well. Thanks for your reply. 👍
