### ISSUE TITLE
Spring Turbine dashboard not working

### ISSUE THREAD

**Issue by JagmohanSharma** [spring-cloud/spring-cloud-release#58]
I am facing some issue while working on turbine dashboard. As I am able to get turbine stream for given cluster but not able to see anything on dashboard as it is just getting loaded as shown in below screenshots. Kindly help if any configuration is missing. 

Below are my configurations:

config.properties

turbine.aggregator.clusterConfig=SpringHystrixDemo2
turbine.instanceUrlSuffix=:9080/hystrix.stream
turbine.EurekaInstanceDiscovery.hystrix2.instances=localhost
InstanceDiscovery.impl=com.netflix.turbine.discovery.EurekaInstanceDiscovery.class
turbine.InstanceMonitor.eventStream.skipLineLogic.enabled=false

Application.yml

server:
port: 8080

turbine:
aggregator:
clusterConfig: SPRINGHYSTRIXDEMO2
clusterNameExpression: new String("default")
appConfig: SpringHystrixDemo2

InstanceMonitor:
eventStream:
skipLineLogic:
enabled: false

bootstrap.yml

spring:
application:
name: SpringTurbine
cloud:
config:
discovery:
enabled: true

eureka:
instance:
nonSecurePort: ${server.port:8080}
client:
serviceUrl:
defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

Application.java

@SpringBootApplication
@EnableHystrix
@EnableEurekaClient
@EnableHystrixDashboard
@EnableTurbine
public class DemoApplication {

public static void main(String[] args) {
    SpringApplication.run(DemoApplication.class, args);
}
}

For cluster SpringHystrixDemo2 I have configured it in different application running on other port:

application.yml

server:
port: 9080

hystrix:
command:
RemoteMessageClientCommand:
execution:
isolation:
thread:
timeoutInMilliseconds: 5000
RemoteMessageAnnotationClient:
execution:
isolation:
thread:
timeoutInMilliseconds: 5000

bootstrap.yml

  spring:
    application:
      name: SpringHystrixDemo2
    cloud:
      config:
        enabled: true
        discovery:
          enabled: true
          serviceId: SPRINGCONFIGSERVER

  eureka:
    instance:
      nonSecurePort: ${server.port:9080}
    client:
      serviceUrl:
        defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
Application.java

@SpringBootApplication
@EnableHystrix
@EnableHystrixDashboard
@EnableEurekaClient
@EnableDiscoveryClient
public class DemoApplication {

public static void main(String[] args) {
    SpringApplication.run(DemoApplication.class, args);
}
}

I have configured eureka server on 8761 port. which is lisening all other eureka client.as

<img width="1172" alt="screen shot 2016-06-06 at 5 53 58 pm" src="https://cloud.githubusercontent.com/assets/19706178/15822132/a597df2c-2c11-11e6-8f43-c292b6ab54ec.png">

This is how I am not able to see any turbine dashboard. as it is just getting loaded.
<img width="1174" alt="screen shot 2016-06-06 at 5 54 10 pm" src="https://cloud.githubusercontent.com/assets/19706178/15822137/ab37591c-2c11-11e6-840b-31b7d94c8a92.png">

Stream view.--
<img width="1171" alt="screen shot 2016-06-06 at 5 54 19 pm" src="https://cloud.githubusercontent.com/assets/19706178/15822142/b2644498-2c11-11e6-8bee-1c6848780b0e.png">
<img width="1175" alt="screen shot 2016-06-06 at 5 54 39 pm" src="https://cloud.githubusercontent.com/assets/19706178/15822146/b2bdb6e0-2c11-11e6-9da5-7568cbc00c6a.png">

**Comment by spencergibb** [comment]
Why are you setting `InstanceDiscovery.impl`?

**Comment by JagmohanSharma** [comment]
Actually as we have differenct approach for instance discovery as EurekaInstanceDiscovery or FileBasedInstanceDiscovery or ConfigPropertyBasedDiscovery. so as per given in https://github.com/Netflix/Turbine/wiki/Configuration-(1.x) I used this parameter. Dont we need this ?

**Comment by spencergibb** [comment]
you shouldn't if you are using `@EnableTurbine`.

**Comment by dsyer** [comment]
Can we move this discussion to spring-cloud-netflix, if it is still active?
