### ISSUE TITLE
Integration test doesn't find the Application class

### ISSUE THREAD

**Issue by LucasHCruz** [spring-cloud/spring-cloud-release#65]
Guys.. after upgrade my version of spring cloud from Brixton.SR5 to Camden.SR2 my integration doesn't find the Application.class

My sample application is: https://github.com/LucasHCruz/stack40664101

**Comment by spencergibb** [comment]
Can you provide more details? Which integration test? Errors? Was spring cloud the only change or was boot changed as well?

**Comment by LucasHCruz** [comment]
It's the only change.

When I run with maven command `mvn clean install -P integration` I'm getting:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project mp-schedule-integration-test: Compilation failure: Compilation failure:
[ERROR] /Users/lcruz/Dev/professional/cnova/marketplace/projetos/mp-schedule/mp-schedule-integration-test/src/test/java/com/cnova/mpschedule/test/util/IntegrationTestCommon.java:[5,28] cannot find symbol
[ERROR] symbol:   class Application
[ERROR] location: package com.cnova.mpschedule
```

**Comment by spencergibb** [comment]
I ran that command just fine on your project. What version of maven are you using?

**Comment by LucasHCruz** [comment]
3.3.9

**Comment by spencergibb** [comment]
I can't recreate it.

**Comment by LucasHCruz** [comment]
Sorry man...My Application was commented in test.. try again please!!!

This is the Travis of the project: https://travis-ci.org/LucasHCruz/stack40664101

**Comment by spencergibb** [comment]
your integration test module is commented out too

**Comment by spencergibb** [comment]
I see the module in the profile, but I get the same error with Brixton.

**Comment by LucasHCruz** [comment]
I missed the version of Spring Boot... I found it... when I changed the version from 1.3.8 to 1.4.0 ++ the error occurred...

Thank you for attention
