### ISSUE TITLE
Update the maven-git-commit-id-plugin to the latest version

### ISSUE THREAD

**Issue by tjuchniewicz** [spring-cloud/spring-cloud-release#67]
Now we use older version which is affected by security issue: https://github.com/ktoso/maven-git-commit-id-plugin/issues/240

Please update to 2.2.1.

I'm not sure where this dependency is defined.

**Comment by shakuzen** [comment]
The plugin is managed [in the `spring-boot-starter-parent` POM](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-starters/spring-boot-starter-parent/pom.xml#L135).
Hence, this issue should be opened with the [Spring Boot issue tracker](https://github.com/spring-projects/spring-boot/issues) if you want them to consider upgrading the git-commit-id-plugin's version.

**Comment by tjuchniewicz** [comment]
Thanks @shakuzen. Moving issue to Spring Boot project: https://github.com/spring-projects/spring-boot/issues/7980
