### ISSUE TITLE
Could not resolve: org.springframework.cloud:spring-cloud-starter-consul

### ISSUE THREAD

**Issue by rajnish-kumar-76** [spring-cloud/spring-cloud-release#72]
Hi,
I am using gradle to build. Gradle reports not able to resolve consul related dependency. Tried both consul-all and consul-dependency. Both reported similar errors.
```
Could not resolve: org.springframework.cloud:spring-cloud-starter-consul-all
Could not resolve: org.springframework.cloud:spring-cloud-starter-consul-discovery:
```
build.gradle snapsot :-
```
dependencies {
    compile("org.springframework.boot:spring-boot-starter-web")
    compile("org.springframework.cloud:spring-cloud-starter-consul-all")
    //compile("org.springframework.cloud:spring-cloud-starter-consul-discovery")
    // tag::actuator[]
    //compile("org.springframework.boot:spring-boot-starter-actuator")
    // end::actuator[]
    // tag::tests[]
    testCompile("org.springframework.boot:spring-boot-starter-test")
    // end::tests[]
}
```
Thanks.

**Comment by spencergibb** [comment]
They are maven central. You have said what BOM version you are using either. Please show your whole build file.

**Comment by alok001** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.micro</groupId>
  <artifactId>SpringMicroService</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>SpringMicroService</name>
  <description>Spring boot</description>
  
  
  <parent>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-parent</artifactId>
        <version>Brixton_.RELEASE</version>  
    </parent>
    <dependencies>
        <dependency>
            
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter</artifactId>
        </dependency>

        <dependency>
            
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-eureka-server</artifactId>
        </dependency>
    </dependencies>
    
    <properties>  
    	<java.version>1.8</java.version>  
	</properties>
  
</project>

This is pom.xml. It shows error

Error: Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.springframework.cloud:spring-cloud-starter-parent:pom:Brixton_.RELEASE in central (https://repo.maven.apache.org/maven2)

Kindly help to sort this. Went through couple of blogs but with no help.

**Comment by spencergibb** [comment]
No underscore in name. Brixton is no longer supported.

**Comment by alok001** [comment]
Hi 

How i am supposed to configure spring cloud in pom.xml. Could you please refer or suggest.

**Comment by ryanjbaxter** [comment]
You can see how to setup the POM here http://projects.spring.io/spring-cloud/.  Pick the version of Spring Cloud you want to use and copy the XML.

**Comment by alok001** [comment]
Hi Ryan

The issue is resolved now. Below is what i did

1) Deleted .m2(local repo) folder
2) run the command mvn package
3) after that update maven of the project

Worked for me , seems some of the jars are broken. Nothing was wrong with
pom.xml

Regards
Alok Mazumdar

**Comment by srinivasvadla** [comment]
Hai all .
could you pleases help out this error  in pom.xml , iam using spring boot with eureka when iam adding the below dependency it is saying --:Project build error: 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-starter-eureka:jar is missing.

<dependency>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-starter-eureka</artifactId>
</dependency>
	
My Boot version is below one 
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>2.1.0.RELEASE</version>
	<relativePath/>
</parent>

Thank you,
Srinivas.

**Comment by spencergibb** [comment]
In the future, please don't comment on old closed issues. Has nothing to do with the boot version.

https://github.com/spring-projects/spring-cloud/wiki/Spring-Cloud-Edgware-Release-Notes#renamed-starters
