### ISSUE TITLE
Update mvnw to 3.5.0

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release#75]
```
distributionUrl=https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.5.0/apache-maven-3.5.0-bin.zip
```

**Comment by meletis** [comment]
I can see this project is already using 3.8.4 (https://github.com/spring-cloud/spring-cloud-release/blob/v2023.0.2/.mvn/wrapper/maven-wrapper.properties), so I guess this old issue can be closed now?
