### ISSUE TITLE
Simpler version names

### ISSUE THREAD

**Issue by jayanderson** [spring-cloud/spring-cloud-release#77]
I was confused when I first encountered the version names with spring cloud. I didn't immediately know when version I should be using (Camden or Brixton or Dalston?). In the end it wasn't terribly difficult to figure out (major releases go in alphabetic order--similar to eclipse), but I'd prefer more tradition version numbering to more immediately understand what version I should be at. It's at least worth considering to reduce some small burden on users.

See also:
- https://opensource.com/business/16/3/kill-off-extra-brand-names
- https://kichwacoders.com/2016/04/28/why-its-time-to-kill-the-eclipse-release-namesneon-oxygen-etc/

**Comment by spencergibb** [comment]
Added #78 to document the versioning scheme. We also need to include this repo's docs to the combined documentation #69.

You'd have to convince other spring/pivotal projects to move as well.

We switched to this specifically to move away from numbers.

> The BOM can be imported in Maven, which will provide a set of default artifact versions to use whenever the corresponding dependency is added to a pom without an explicitly provided version.
> As the different artifacts versions are not necessarily aligned, the BOM represents a release train with a codename-based versioning scheme: the usual MAJOR.MINOR numbers are replaced by a chemical name from `<pick your naming scheme>`, in growing alphabetical order.
> The first stable release is simply suffixed with -RELEASE, but the equivalent of patch releases are also possible as "Service Releases", appending the suffix -SR followed by the number of the service release (eg. -SR1, -SR2)

- https://github.com/reactor/reactor#bom-versionning-scheme
- https://cloud.spring.io/spring-cloud-stream/
- http://platform.spring.io/platform/
- https://projects.spring.io/spring-cloud/
