### ISSUE TITLE
Consider deriving the spring-cloud-dependencies from platform-bom

### ISSUE THREAD

**Issue by alwaysastudent** [spring-cloud/spring-cloud-release#80]
It would be nice if you give out the compatible platform-bom dependencies from this release train by deriving your projects out of platform bom. An issue was created to have platform ship the cloud dependencies as well but got closed saying the cloud projects are at a higher level. 
Quoting  @dsyer
>This will probably not happen (or at least not yet) because Spring Cloud is kind of a higher level in the stack. It doesn't explicitly depend on Spring IO, but in principle it could.

Please refer to

- https://github.com/spring-io/platform/issues/574 
- https://github.com/spring-io/platform/issues/232

**Comment by spencergibb** [comment]
I don't think this is going to change. We document how to use the platform bom https://github.com/spring-cloud/spring-cloud-release/blob/master/docs/src/main/asciidoc/spring-cloud-starters.adoc#using-spring-cloud-dependencies-with-spring-io-platform
