### ISSUE TITLE
errors after move from Brixton to Camden

### ISSUE THREAD

**Issue by mikesockor** [spring-cloud/spring-cloud-release#81]
seems problem with dependencies

i have got a lot of compilation errors with module which depends on other eureka module

with Brixton all is fine, i checked 3 times, rolled back and reproduced again

https://github.com/mikesockor/SOFc
```
COMPILATION ERROR :
` ``

**Comment by rotilho** [comment]
I don't think it's connected somehow with spring-cloud. I guess you are removing the dependency which have the packages io.upzel.crmRecords.*

**Comment by mikesockor** [comment]
it happened when i changing version of spring-clound, nothing more
as i said, i can reproduce it

with Brixton.SR7 working fine

**Comment by spencergibb** [comment]
@mikesockor Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Nothing in your very long log suggests that the problem is caused by spring cloud. I'd guess you might have a corrupt maven cache. Otherwise, please provide a sample project that recreates the problem.

**Comment by mikesockor** [comment]
https://github.com/mikesockor/SOFc

just change from Brixton to Camden in pom's and try to mvn clean install

**Comment by spencergibb** [comment]
You shouldn't use spring-cloud as your parent

import the bom like so:
```
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
```

**Comment by mikesockor** [comment]
thank you a lot
working fine

repo has been updated
