### ISSUE TITLE
SNAPSHOT dependencies in Edgware.M1 pom.xml

### ISSUE THREAD

**Issue by poznachowski** [spring-cloud/spring-cloud-release#84]
I think that something went wrong with Edgware M1 release. `pom.xml` from GH looks good: https://github.com/spring-cloud/spring-cloud-release/blob/Edgware.M1/spring-cloud-dependencies/pom.xml However repository version contains SNAPSHOT dependencies: https://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-dependencies/Edgware.M1/spring-cloud-dependencies-Edgware.M1.pom

**Comment by marcingrzejszczak** [comment]
Check it now - should be no SNAPSHOTs any longer
