### ISSUE TITLE
Edgware SR4 with Spring Boot 1.5.13

### ISSUE THREAD

**Issue by jjroldan1** [spring-cloud/spring-cloud-release#94]
Hi,

Are there any plans to release a service release in Edgware that will target Spring Boot 1.5.13 following the security vulnerabilities published?

In my project we follow scrupulously the guidelines by http://projects.spring.io/spring-cloud/ and I would really regret to deviate by  managing the parent pom without seeing it published/certified there.

Thanks!
Juan.

**Comment by spencergibb** [comment]
We likely will, but don't let that keep you from using the new boot version with the latest SR.

**Comment by jjroldan1** [comment]
Thanks, will give it a try!
