### ISSUE TITLE
Release planning Spring Cloud Finchley

### ISSUE THREAD

**Issue by sanderino666** [spring-cloud/spring-cloud-release#96]
Hi guys,

We are waiting patiently on the Spring Cloud Finchley release by watching https://github.com/spring-cloud/spring-cloud-release/milestones but we've noticed the mentioned release dates are, at least for the last couple of months, never met. 

Because we used these dates to actually set our own product release date, you can image we're a bit in a squeeze right now because the release date of Finchley was set to the beginning of April and is moving further and further into the future.

Next to that, we also saw that Finchley RC2 umbrella project is not released while subproject are released a few days ago.

Could you give us an update on Finchley RC2 and what the planning will be for the Finchley GA?

Thanks!

Sander

**Comment by sanderino666** [comment]
@spencergibb @ryanjbaxter @dsyer Any thoughts on this?

**Comment by spencergibb** [comment]
RC 2 is out, but unannounced. We move dates based on various factors so that we have a good release. The dates are never hard and firm and shouldn't be relied as such.

**Comment by spencergibb** [comment]
We needed multiple fixes from upstream projects, including reactor, framework and boot. We also had PRs that our commercial team needed to get in. Some of the team were also traveling this month. Trust me, we want to release as soon as we can. The estimates in the milestones are the best I can gone you. The team will communicate this week and provide an update. We have to provide an opportunity for feedback based on changes.

**Comment by vdotjansen** [comment]
More info can be found here: https://github.com/orgs/spring-cloud/projects/7
Source: https://twitter.com/springcloud/status/1002234327416168449?s=19
